# Original theme somewhere here https://github.com/romainl/Apprentice

[colors]
  [colors.primary]
    background = "0x323232"
    foreground = "0xc8c8c8"

  [colors.cursor]
    text = "0xfeffff"
    cursor = "0xc7c7c7"

  [colors.normal]
    black = "0x252525"
    blue = "0xbe7472"

    cyan = "0x709772"
    green = "0x989772"
    magenta = "0x7199bc"
    red = "0x727399"
    white = "0x719899"
    yellow = "0x7f7f7f"

  [colors.bright]
    black = "0x555555"
    blue = "0xff9900"
    cyan = "0x97bb98"
    green = "0xfefdbc"
    magenta = "0x9fbdde"
    red = "0xaf5f5f"
    white = "0x6fbbbc"
    yellow = "0xfeffff"

