[colors]
  [colors.primary]
    background = "0xFFFFFF"
    foreground = "0x333333"

  [colors.normal]
    black   = "0x000000"
    red     = "0xC50F1F"
    green   = "0x13A10E"
    yellow  = "0xC19C00"
    blue    = "0x0037DA"
    magenta = "0x881798"
    cyan    = "0x3A96DD"
    white   = "0xCCCCCC"

  [colors.bright]
    black   = "0x767676"
    red     = "0xE74856"
    green   = "0x16C60C"
    yellow  = "0xF9F1A5"
    blue    = "0x3B78FF"
    magenta = "0xB4009E"
    cyan    = "0x61D6D6"
    white   = "0xF2F2F2"

  [colors.cursor]
    text = "0xFFFFFF"
    cursor = "0x333333"

  [colors.selection]
    text = "0xFFFFFF"
    background = "0xADD6FF"
